import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/students');
await page.waitForTimeout(1500);
const row = page.locator('tr', { hasText: 'طالب اختبار QA معدل' }).first();
const html = await row.innerHTML();
const idx = html.indexOf('data-confirm-delete');
console.log('HTML from data-confirm-delete:', html.replace(/\s+/g, ' ').slice(idx - 400, idx + 700));
await browser.close();