import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/sales/create');
await page.waitForTimeout(2500);
const html = await page.content();
const markers = ['course-card', 'addToCart', 'courseSelect', 'courses', 'course', 'select'];
for (const m of markers) console.log(m, ':', html.includes(m) ? (html.match(new RegExp(m + '[^>]{0,60}', 'g')) || []).slice(0, 3) : 'ABSENT');
const idx = html.indexOf('addToCart');
console.log('addToCart ctx:', idx > -1 ? html.slice(idx - 200, idx + 200).replace(/\s+/g, ' ') : 'none');
await browser.close();