import { newBrowser, login, fetchAs, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
page.setDefaultTimeout(20000);
await login(page);
await page.goto(BASE + '/students');
await page.waitForTimeout(1500);
const row = page.locator('tr', { hasText: 'طالب اختبار QA معدل' }).first();
console.log('row:', await row.count());
const delBtn = row.locator('button[data-confirm-delete]').first();
await delBtn.evaluate((el) => el.click());
await page.waitForTimeout(1000);
console.log('swal visible:', await page.locator('.swal2-popup').isVisible().catch(() => false));
console.log('swal title:', (await page.locator('.swal2-title').innerText().catch(() => 'ERR')).slice(0, 80));
console.log('confirm count:', await page.locator('.swal2-confirm').count());
console.log('confirm text:', (await page.locator('.swal2-confirm').innerText().catch(() => 'ERR')).slice(0, 60));
page.on('request', (r) => { if (r.method() !== 'GET') console.log('REQ', r.method(), r.url().replace('http://demo-center.localhost:8000', '')); });
page.on('response', (r) => { if (r.request().method() !== 'GET') console.log('RESP', r.status(), r.request().method(), r.url().replace('http://demo-center.localhost:8000', '')); });
await page.locator('.swal2-confirm').click();
await page.waitForTimeout(3000);
console.log('url after:', page.url());
const r = await fetchAs(page, BASE + '/students/search?q=' + encodeURIComponent('طالب اختبار QA معدل'));
console.log('search after:', JSON.stringify(r.body).slice(0, 200));
await browser.close();