import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/students');
await page.waitForTimeout(1500);
const row = page.locator('tr', { hasText: 'طالب اختبار QA معدل' }).first();
const html = await row.innerHTML();
const clean = html.replace(/\s+/g, ' ');
const idx = clean.indexOf('data-confirm-delete');
console.log(clean.slice(Math.max(0, idx - 900), idx + 300));
await browser.close();