import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/sales/create');
await page.waitForTimeout(2500);
console.log('url:', page.url());
const title = await page.title().catch(() => 'ERR');
console.log('title:', title);
const body = await page.locator('body').innerText();
console.log('BODY START:', body.slice(0, 600).replace(/\n/g, ' | '));
await browser.close();