import { newBrowser, login, fetchAs, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
const r = await fetchAs(page, BASE + '/students/search?q=' + encodeURIComponent('طالب اختبار QA'));
const s = Array.isArray(r.body) && r.body.length ? r.body[0] : null;
console.log('found:', JSON.stringify(s));
if (!s) { await browser.close(); process.exit(0); }
await page.goto(BASE + '/students/' + s.id + '/edit');
await page.waitForTimeout(1500);
console.log('edit url:', page.url());
const nameVal = await page.locator('input[name="name"]').inputValue().catch(() => 'ERR');
console.log('name field:', nameVal);
const phoneVal = await page.locator('input[name="phone"]').inputValue().catch(() => 'ERR');
console.log('phone field:', phoneVal);
const gradeSel = await page.locator('#main_grade_select').count();
console.log('grade select count:', gradeSel);
const newName = 'طالب اختبار QA معدل';
await page.fill('input[name="name"]', newName);
const f = page.locator('form').first();
const btns = await f.locator('button[type="submit"]').count();
console.log('submit buttons in first form:', btns);
await f.locator('button[type="submit"]').first().click().catch(async () => { await page.click('#btnSubmitStudent'); });
await page.waitForTimeout(3000);
console.log('after submit url:', page.url());
const body = await page.locator('body').innerText();
const err = (body.match(/(هناك[^\n]{0,120}|تحقق[^\n]{0,120}|errors?[^\n]{0,80})/gi) || ['(no error text)'])[0];
console.log('error hint:', err.slice(0, 200));
const r2 = await fetchAs(page, BASE + '/students/search?q=' + encodeURIComponent('طالب اختبار QA معدل'));
console.log('search after edit:', JSON.stringify(r2.body).slice(0, 300));
await browser.close();