import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/students/create');
await page.waitForTimeout(1200);
await page.fill('input[name="name"]', 'طالب فلاش اختبار');
await page.fill('input[name="phone"]', '01055550000');
await page.locator('#main_grade_select').selectOption({ index: 1 });
await page.click('.btn-next-step');
await page.waitForTimeout(400);
await page.locator('.course-checkbox-item').first().check();
await page.click('#btnSubmitStudent');
await page.waitForNavigation({ waitUntil: 'load', timeout: 20000 }).catch(() => {});
await page.waitForTimeout(800);
console.log('URL:', page.url());
const flash = await page.locator('.flash-messages-container').count();
console.log('flash container:', flash);
const flashText = await page.locator('.alert.alert-success').innerText().catch(() => '(none)');
console.log('success alert text:', flashText.replace(/\n/g, ' | '));
const generated = await page.locator('body').innerText();
console.log('has generated password section:', /كلمة المرور|password/i.test(generated));
await browser.close();
