import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/sales/create');
await page.waitForTimeout(2500);
const html = await page.content();
const idx = html.indexOf('select_courses');
console.log('title idx:', idx);
console.log(html.slice(idx - 300, idx + 2500).replace(/\s+/g, ' '));
await browser.close();