import { newBrowser, login, BASE } from './qa_helpers.mjs';
const { browser, page } = await newBrowser();
await login(page);
await page.goto(BASE + '/students/create');
await page.waitForTimeout(1500);
const opts = await page.locator('#main_grade_select option').count();
console.log('option count:', opts);
const values = await page.locator('#main_grade_select option').evaluateAll(els => els.map(e => e.value + ':' + e.text).slice(0, 8));
console.log('options:', JSON.stringify(values));
const disabled = await page.locator('#main_grade_select').isDisabled();
console.log('disabled:', disabled);
await browser.close();
