import defaultTheme from 'tailwindcss/defaultTheme';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
        './resources/js/**/*.js',
        './resources/js/**/*.jsx',
        './resources/js/**/*.ts',
        './resources/js/**/*.tsx',
        './Modules/**/resources/views/**/*.blade.php',
        './Modules/**/resources/views/**/*.php',
        './Modules/**/resources/assets/**/*.{js,ts,vue,scss,css}',
    ],
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1rem',
                sm: '1.5rem',
                lg: '2rem',
            },
            screens: {
                sm: '640px',
                md: '768px',
                lg: '1024px',
                xl: '1280px',
                '2xl': '1440px',
            },
        },
        extend: {
            fontFamily: {
                sans: ['Cairo', 'Inter', 'Tajawal', ...defaultTheme.fontFamily.sans],
                cairo: ['Cairo', 'sans-serif'],
                inter: ['Inter', 'sans-serif'],
                tajawal: ['Tajawal', 'sans-serif'],
                arabic: ['Cairo', 'Tajawal', 'sans-serif'],
            },
            colors: {
                brand: {
                    50: '#F5F6FF',
                    100: '#EEF0FF',
                    200: '#D7D9FD',
                    300: '#B4B8FB',
                    400: '#8185F7',
                    primary: '#5B5FEF',
                    secondary: '#4548C7',
                    500: '#5B5FEF',
                    600: '#4548C7',
                    700: '#3638A0',
                    800: '#2A2B7C',
                    900: '#1E1F57',
                    indigo: '#5B5FEF',
                    snow: '#F8FAFC',
                    dark: '#111827',
                    muted: '#94A3B8',
                    secondary_text: '#475569',
                    bg: '#F8FAFC',
                    border: '#E2E8F0',
                    card: '#FFFFFF',
                },
                slate: {
                    ...defaultTheme.colors?.slate,
                    950: '#0D1A2B',
                },
                divider: "hsl(var(--divider))",
                border: "hsl(var(--border))",
                input: "hsl(var(--input))",
                ring: "hsl(var(--ring))",
                background: "hsl(var(--background))",
                foreground: "hsl(var(--foreground))",
                primary: {
                    DEFAULT: "hsl(var(--primary))",
                    foreground: "hsl(var(--primary-foreground))",
                },
                secondary: {
                    DEFAULT: "hsl(var(--secondary))",
                    foreground: "hsl(var(--secondary-foreground))",
                },
                destructive: {
                    DEFAULT: "hsl(var(--destructive))",
                    foreground: "hsl(var(--destructive-foreground))",
                },
                success: {
                    DEFAULT: "hsl(var(--success, 142 71% 45%))",
                    foreground: "#FFFFFF",
                },
                warning: {
                    DEFAULT: "hsl(var(--warning, 38 92% 50%))",
                    foreground: "#FFFFFF",
                },
                info: {
                    DEFAULT: "hsl(var(--info, 199 89% 48%))",
                    foreground: "#FFFFFF",
                },
            },
            borderRadius: {
                xs: "6px",
                sm: "8px",
                md: "10px",
                lg: "12px",
                xl: "16px",
                "2xl": "20px",
                card: "16px",
                modal: "20px",
                btn: "10px",
                input: "10px",
                full: "9999px",
            },
            boxShadow: {
                'elevation-0': 'none',
                'elevation-1': '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
                'elevation-2': '0 4px 6px -1px rgba(0, 0, 0, 0.07), 0 2px 4px -2px rgba(0, 0, 0, 0.05)',
                'elevation-3': '0 10px 15px -3px rgba(0, 0, 0, 0.08), 0 4px 6px -4px rgba(0, 0, 0, 0.04)',
                'elevation-4': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.04)',
                'elevation-5': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
                xs: '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
                sm: '0 1px 3px 0 rgba(15, 23, 42, 0.06), 0 1px 2px -1px rgba(15, 23, 42, 0.04)',
                md: '0 4px 6px -1px rgba(15, 23, 42, 0.07), 0 2px 4px -2px rgba(15, 23, 42, 0.05)',
                lg: '0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.04)',
                xl: '0 20px 25px -5px rgba(15, 23, 42, 0.1), 0 8px 10px -6px rgba(15, 23, 42, 0.04)',
            },
        },
    },
    plugins: [],
};
