<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Third Party Services
    |--------------------------------------------------------------------------
    |
    | This file is for storing the credentials for third party services such
    | as Mailgun, Postmark, AWS and more. This file provides the de facto
    | location for this type of information, allowing packages to have
    | a conventional file to locate the various service credentials.
    |
    */

    'postmark' => [
        'key' => env('POSTMARK_API_KEY'),
    ],

    'resend' => [
        'key' => env('RESEND_API_KEY'),
    ],

    'ses' => [
        'key' => env('AWS_ACCESS_KEY_ID'),
        'secret' => env('AWS_SECRET_ACCESS_KEY'),
        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
    ],

    'slack' => [
        'notifications' => [
            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),
            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),
        ],
    ],

    'gemini' => [
        'api_key' => env('GEMINI_API_KEY'),
    ],

    'stripe' => [
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
        'price_basic' => env('STRIPE_PRICE_BASIC'),
        'price_pro' => env('STRIPE_PRICE_PRO'),
        'demo_mode' => env('STRIPE_DEMO_MODE', false),
    ],

    'telegram' => [
        'bot_token' => env('TELEGRAM_BOT_TOKEN'),
        'admin_chat_id' => env('TELEGRAM_ADMIN_CHAT_ID'),
    ],

    'google' => [
        'client_id' => env('GOOGLE_CLIENT_ID'),
        'client_secret' => env('GOOGLE_CLIENT_SECRET'),
        'redirect' => env('GOOGLE_REDIRECT_URI'),
    ],

    'paypal' => [
        'client_id' => env('PAYPAL_CLIENT_ID'),
        'client_secret' => env('PAYPAL_CLIENT_SECRET'),
        'mode' => env('PAYPAL_MODE', 'sandbox'),
        'webhook_id' => env('PAYPAL_WEBHOOK_ID'),
    ],

    'paymob' => [
        'api_key' => env('PAYMOB_API_KEY'),
        'hmac_secret' => env('PAYMOB_HMAC_SECRET'),
        'merchant_id' => env('PAYMOB_MERCHANT_ID'),
        'card_integration_id' => env('PAYMOB_CARD_INTEGRATION_ID'),
        'wallet_integration_id' => env('PAYMOB_WALLET_INTEGRATION_ID'),
        'iframe_id' => env('PAYMOB_IFRAME_ID'),
    ],

    'klaviyo' => [
        'key' => env('KLAVIYO_API_KEY'),
    ],

    'whatsapp' => [
        'system_token' => env('WHATSAPP_SYSTEM_TOKEN'),
        'system_phone_id' => env('WHATSAPP_SYSTEM_PHONE_ID'),
        'system_version' => env('WHATSAPP_SYSTEM_VERSION', 'v21.0'),
        'system_country_code' => env('WHATSAPP_SYSTEM_COUNTRY_CODE', '20'),
    ],

    'onboarding' => [
        'emails_enabled' => env('ENABLE_ONBOARDING_EMAILS', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Online Classes — Zoom + Recording Storage
    |--------------------------------------------------------------------------
    |
    | All Zoom credentials stay server-side. The browser only ever receives
    | short-lived SDK signatures generated by ZoomService.
    |
    */
    'zoom' => [
        // Server-to-Server OAuth app (meeting creation, recordings, webhooks)
        'account_id' => env('ZOOM_ACCOUNT_ID'),
        'client_id' => env('ZOOM_CLIENT_ID'),
        'client_secret' => env('ZOOM_CLIENT_SECRET'),
        // Meeting SDK JWT credentials (embedded client signature)
        'sdk_key' => env('ZOOM_SDK_KEY'),
        'sdk_secret' => env('ZOOM_SDK_SECRET'),
        // Webhook secret token (endpoint validation + payload signature)
        'webhook_secret_token' => env('ZOOM_WEBHOOK_SECRET_TOKEN'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Recorded Videos — Bunny Stream
    |--------------------------------------------------------------------------
    |
    | All Bunny Stream credentials stay server-side. The browser only ever receives
    | short-lived TUS upload tokens generated by BunnyStreamProvider.
    |
    */
    'bunny' => [
        'library_id' => env('BUNNY_LIBRARY_ID'),
        'api_key' => env('BUNNY_API_KEY'),
        'collection_id' => env('BUNNY_COLLECTION_ID'),
    ],

    'recordings' => [
        // auto = first configured cloud disk (r2 then s3), else local disk.
        'driver' => env('RECORDINGS_STORAGE_DRIVER', 'auto'),
        'url_ttl' => env('RECORDINGS_URL_TTL', 300),
    ],

    'r2' => [
        'key' => env('R2_ACCESS_KEY_ID'),
        'secret' => env('R2_SECRET_ACCESS_KEY'),
    ],

];