@extends('layouts.landing-new')

@section('content')
    @include('landing.partials.hero')
    @include('landing.partials.pain-points')
    @include('landing.partials.outcome')
    @include('landing.partials.whatsapp-killer')
    @include('landing.partials.payments-attendance')
    @include('landing.partials.excel-migration')
    @include('landing.partials.features')
    @include('landing.partials.automation')
    @include('landing.partials.trust')
    @include('landing.partials.pricing')
    @include('landing.partials.faq')
    @include('landing.partials.cta')
@endsection
