<?php

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Arr;

$langDirs = [
    'core' => __DIR__ . '/resources/lang',
    'center' => __DIR__ . '/Modules/Center/resources/lang'
];

$translations = [
    'fr' => [
        'core/admin.php' => [
            'price_monthly' => 'Prix Mensuel',
            'price_yearly' => 'Prix Annuel',
            'old_price' => 'Ancien Prix',
            'discount_label' => 'Étiquette de Réduction',
            'trial_days' => 'Jours d\'Essai',
            'sort_order' => 'Ordre de Tri',
            'is_default' => 'Forfait par Défaut',
            'delete_package' => 'Supprimer le Forfait',
            'delete_package_confirm' => 'Voulez-vous vraiment supprimer ce forfait ?',
            'custom_cta_section' => 'Lien d\'abonnement personnalisé',
            'cta_text_placeholder' => 'Texte du bouton',
            'cta_link_placeholder' => 'Lien (URL ou WhatsApp)',
            'description_ar' => 'Description (AR)',
            'description_en' => 'Description (EN)',
            'package_name_ar' => 'Nom du Forfait (AR)',
            'package_name_en' => 'Nom du Forfait (EN)',
            'system_features_tab' => 'Fonctionnalités du Système',
            'system_features_management' => 'Gestion des Fonctionnalités',
            'system_features_note' => 'Contrôlez les fonctionnalités qui apparaissent dans la table de comparaison',
            'feature_name' => 'Nom de la Fonctionnalité',
            'feature_code' => 'Code de la Fonctionnalité',
            'type' => 'Type',
            'category' => 'Catégorie',
            'limit_type' => 'Numérique',
            'boolean_type' => 'Oui/Non',
            'new_package' => 'Nouveau Forfait',
            'new_feature' => 'Nouvelle Fonctionnalité',
            'save_all' => 'Tout Enregistrer',
            'note' => 'Note',
            'one_feature_per_line' => 'Une fonctionnalité par ligne.',
            'base_price' => 'Prix de Base',
            'base_pricing' => 'Tarification de Base',
            'price' => 'Prix',
            'days' => 'Jours',
            'slug' => 'Slug',
            'slug_placeholder' => 'Exemple: starter-plan',
            'close' => 'Fermer',
            'create' => 'Créer',
            'add' => 'Ajouter',
            'category_core' => 'Principal',
            'category_smart' => 'Intelligent',
            'category_analysis' => 'Analyse',
            'category_academic' => 'Académique',
            'no_coupons_hint' => 'Aucun coupon',
            'coupon_code_hint' => 'Code Coupon',
            'coupon_name_hint' => 'Nom Interne',
            'max_uses_hint' => 'Utilisations Max',
            'generate' => 'Générer',
            'coupon_applied' => 'Coupon appliqué !',
            'invalid_coupon' => 'Coupon invalide',
            'expired_coupon' => 'Coupon expiré',
            'enter_coupon_code' => 'Entrez le code',
            'coupon_not_for_plan' => 'Non applicable pour ce forfait',
            'students' => 'Étudiants',
            'instructors' => 'Instructeurs',
            'regional_prices' => 'Prix Régionaux',
            'auto_detected' => 'Détection Automatique'
        ],
        'core/auth.php' => [
            'failed' => 'Ces identifiants ne correspondent pas à nos enregistrements.',
            'password' => 'Le mot de passe fourni est incorrect.',
            'throttle' => 'Trop de tentatives. Veuillez réessayer dans :seconds secondes.',
            'logout' => 'Se déconnecter',
            'email' => 'Adresse e-mail',
            'remember_me' => 'Se souvenir de moi',
            'forgot_password' => 'Mot de passe oublié ?',
            'two_factor_authentication' => 'Authentification à deux facteurs',
            'verify_code' => 'Vérifier le code',
            'enter_otp' => 'Entrez le code OTP',
            'coupon_error' => 'Erreur lors de la vérification du coupon',
            'register.cta_main' => 'Commencez gratuitement',
            'register.selected_plan' => 'Forfait sélectionné',
            'register.already_have_account' => 'Avez-vous déjà un compte ?',
            'register.terms_prefix' => 'En créant un compte, vous acceptez ',
            'register.terms_of_service' => 'les Conditions d\'utilisation',
            'register.and' => ' et ',
            'register.privacy_policy' => 'la Politique de confidentialité',
            'register.discount' => 'Remise',
            'register.registration_error' => 'Erreur d\'inscription',
            'register.discount_applied' => 'Remise appliquée:',
            'register.save' => 'Économisez',
            'register.join_leaders' => 'Rejoignez les leaders de l\'éducation aujourd\'hui.',
            'register.show' => 'Afficher',
            'register.have_coupon' => 'Avez-vous un coupon ?',
            'register.hide' => 'Masquer',
            'register.confirm_password' => 'Confirmez le mot de passe',
            'register.password_criteria.chars' => '8+ caractères',
            'register.password_criteria.upper' => 'Majuscule',
            'register.password_criteria.lower' => 'Minuscule',
            'register.password_criteria.numbers' => 'Chiffres',
            'register.password_criteria.symbols' => 'Symboles',
            'register.password_criteria.match' => 'Correspondance',
            'register.features.max_students' => 'Nombre max d\'étudiants',
            'register.features.max_instructors' => 'Nombre max d\'instructeurs',
            'register.features.max_courses' => 'Nombre max de cours',
            'register.features.max_classrooms' => 'Nombre max de salles',
            'register.features.max_admins' => 'Membres de l\'administration',
            'register.features.max_branches' => 'Nombre de succursales',
            'register.features.multi_branch' => 'Support multi-succursales',
            'register.features.whatsapp_alerts' => 'Alertes WhatsApp automatisées',
            'register.features.sms_alerts' => 'Alertes SMS automatisées',
            'register.features.attendance_tracking' => 'Système de suivi des présences',
            'register.features.daily_schedules' => 'Gestion des emplois du temps',
            'register.features.financial_reports' => 'Rapports financiers',
            'register.features.advanced_roles' => 'Gestion avancée des rôles',
            'register.features.manage_exams' => 'Gestion des examens',
            'register.features.technical_support' => 'Support technique dédié',
            'register.features.api_access' => 'Accès API',
            'login.admin_login' => 'Connexion Administrateur',
            'registration.success_title' => 'Inscription réussie !',
            'registration.success_subtitle' => 'Votre centre de formation est prêt',
            'registration.your_center_url' => 'L\'URL de votre centre',
            'registration.email' => 'Courriel de l\'administrateur',
            'registration.password' => 'Mot de passe',
            'registration.password_hint' => 'Le mot de passe que vous avez saisi',
            'registration.access_center' => 'Accéder à votre centre',
            'registration.bookmark_hint' => 'Ajoutez ce lien à vos favoris pour un accès rapide',
            'registration.copy' => 'Copier',
            'registration.copied' => 'Copié !',
            'registration.url_copied' => 'L\'URL a été copiée !'
        ],
        'core/dashboard.php' => [
            'dashboard' => 'Tableau de bord',
            'welcome' => 'Bienvenue',
            'students' => 'Étudiants',
            'courses' => 'Cours',
            'instructors' => 'Instructeurs',
            'analytics' => 'Analyses',
            'settings' => 'Paramètres',
            'support' => 'Support technique',
            'tickets' => 'Billets',
            'sales' => 'Ventes',
            'subscription' => 'Abonnement',
            'activity_logs' => 'Journaux d\'activité',
            'profile' => 'Profil'
        ],
        'core/features.php' => [
            'yes' => 'Oui',
            'no' => 'Non',
            'enabled' => 'Activé',
            'disabled' => 'Désactivé',
            'video_support' => 'Support Vidéo',
            'marketing_tools' => 'Outils Marketing',
            'custom_domain' => 'Domaine Personnalisé',
            'remove_branding' => 'Supprimer la Marque'
        ],
        'core/landing.php' => [
            'pricing.per_year' => '/ par an',
            'pricing.equivalent_to' => 'Équivalent à',
            'pricing.month_short' => 'mois',
            'pricing.monthly' => 'Mensuel',
            'pricing.yearly' => 'Annuel',
            'pricing.save_20' => 'Économisez 17%',
            'pricing.days' => 'jours',
            'pricing.unlimited' => 'Illimité',
            'pricing.plans.basic.badge' => 'Populaire',
            'pricing.plans.pro.badge' => 'Pour les Entreprises',
            'pricing.plans.pro.best_value' => 'Meilleur Choix',
            'pricing.comparison.categories.core.features.max_students' => 'Nombre d\'Étudiants',
            'pricing.comparison.categories.core.features.max_admins' => 'Administrateurs',
            'pricing.comparison.categories.core.features.max_courses' => 'Nombre de Cours',
            'pricing.comparison.categories.core.features.storage_limit' => 'Espace de Stockage',
            'pricing.comparison.categories.core.features.max_instructors' => 'Nombre d\'Instructeurs',
            'pricing.comparison.categories.core.features.max_classrooms' => 'Nombre de Salles',
            'pricing.comparison.categories.core.features.advanced_reports' => 'Rapports Avancés',
            'pricing.comparison.categories.core.features.priority_support' => 'Support Prioritaire',
            'pricing.comparison.categories.core.features.multi_branch' => 'Support Multi-succursales',
            'pricing.comparison.categories.smart.features.api_access' => 'Accès API',
            'pricing.comparison.categories.smart.features.whatsapp_alerts' => 'Alertes WhatsApp',
            'pricing.comparison.categories.smart.features.sms_alerts' => 'Alertes SMS',
            'pricing.comparison.categories.analysis.features.financial_reports' => 'Rapports Financiers',
            'pricing.comparison.categories.analysis.features.technical_support' => 'Support Technique',
            'pricing.comparison.plans.free.branches' => false,
            'pricing.comparison.plans.free.sms' => false,
            'pricing.comparison.plans.basic.branches' => false
        ],
        'core/sidebar.php' => [
            'dashboard' => 'Tableau de bord',
            'students' => 'Étudiants',
            'courses' => 'Cours',
            'instructors' => 'Instructeurs',
            'sales' => 'Ventes',
            'reports' => 'Rapports',
            'billing' => 'Facturation',
            'profile' => 'Profil',
            'logout' => 'Déconnexion',
            'panel' => 'Panneau',
            'center_name' => 'Nom du Centre',
            'overview' => 'Aperçu',
            'consent_report' => 'Rapport de Consentement',
            'rights_reserved' => 'Tous droits réservés',
            'developed_by' => 'Développé par'
        ],
        'core/validation.php' => [
            'accepted' => 'Le champ :attribute doit être accepté.',
            'accepted_if' => 'Le champ :attribute doit être accepté quand :other est :value.',
            'active_url' => 'Le champ :attribute n\'est pas une URL valide.',
            'after' => 'Le champ :attribute doit être une date postérieure au :date.',
            'after_or_equal' => 'Le champ :attribute doit être une date postérieure ou égale au :date.',
            'alpha' => 'Le champ :attribute doit contenir uniquement des lettres.',
            'alpha_dash' => 'Le champ :attribute doit contenir uniquement des lettres, des chiffres et des tirets.',
            'alpha_num' => 'Le champ :attribute doit contenir uniquement des chiffres et des lettres.',
            'array' => 'Le champ :attribute doit être un tableau.',
            'ascii' => 'Le champ :attribute ne doit contenir que des caractères alphanumériques et des symboles à un octet.',
            'before' => 'Le champ :attribute doit être une date antérieure au :date.',
            'before_or_equal' => 'Le champ :attribute doit être une date antérieure ou égale au :date.',
            'between.array' => 'Le tableau :attribute doit contenir entre :min et :max éléments.',
            'between.file' => 'La taille du fichier de :attribute doit être comprise entre :min et :max kilo-octets.',
            'between.numeric' => 'La valeur de :attribute doit être comprise entre :min et :max.',
            'between.string' => 'Le texte :attribute doit contenir entre :min et :max caractères.',
            'boolean' => 'Le champ :attribute doit être vrai ou faux.',
            'can' => 'Le champ :attribute contient une valeur non autorisée.',
            'confirmed' => 'Le champ de confirmation :attribute ne correspond pas.',
            'contains' => 'Il manque une valeur requise au champ :attribute.',
            'current_password' => 'Le mot de passe est incorrect.',
            'date' => 'Le champ :attribute n\'est pas une date valide.',
            'date_equals' => 'Le champ :attribute doit être une date égale à :date.',
            'date_format' => 'Le champ :attribute ne correspond pas au format :format.',
            'decimal' => 'Le champ :attribute doit comporter :decimal décimales.',
            'declined' => 'Le champ :attribute doit être refusé.',
            'declined_if' => 'Le champ :attribute doit être refusé quand :other est :value.',
            'different' => 'Les champs :attribute et :other doivent être différents.',
            'digits' => 'Le champ :attribute doit contenir :digits chiffres.',
            'digits_between' => 'Le champ :attribute doit contenir entre :min et :max chiffres.',
            'dimensions' => 'La taille de l\'image :attribute n\'est pas conforme.',
            'distinct' => 'Le champ :attribute a une valeur en double.',
            'doesnt_contain' => 'Le champ :attribute ne doit pas contenir les éléments suivants : :values.',
            'doesnt_end_with' => 'Le champ :attribute ne doit pas se terminer par l\'une des valeurs suivantes : :values.',
            'doesnt_start_with' => 'Le champ :attribute ne doit pas commencer par l\'une des valeurs suivantes : :values.',
            'email' => 'Le champ :attribute doit être une adresse e-mail valide.',
            'ends_with' => 'Le champ :attribute doit se terminer par une des valeurs suivantes : :values',
            'enum' => 'Le champ :attribute sélectionné est invalide.',
            'exists' => 'Le champ :attribute sélectionné est invalide.',
            'extensions' => 'Le champ :attribute doit avoir l\'une des extensions suivantes : :values.',
            'file' => 'Le champ :attribute doit être un fichier.',
            'filled' => 'Le champ :attribute doit avoir une valeur.',
            'gt.array' => 'Le tableau :attribute doit contenir plus de :value éléments.',
            'gt.file' => 'La taille du fichier de :attribute doit être supérieure à :value kilo-octets.',
            'gt.numeric' => 'La valeur de :attribute doit être supérieure à :value.',
            'gt.string' => 'Le texte :attribute doit contenir plus de :value caractères.',
            'gte.array' => 'Le tableau :attribute doit contenir au moins :value éléments.',
            'gte.file' => 'La taille du fichier de :attribute doit être supérieure ou égale à :value kilo-octets.',
            'gte.numeric' => 'La valeur de :attribute doit être supérieure ou égale à :value.',
            'gte.string' => 'Le texte :attribute doit contenir au moins :value caractères.',
            'hex_color' => 'Le champ :attribute doit être une couleur hexadécimale valide.',
            'image' => 'Le champ :attribute doit être une image.',
            'in' => 'Le champ :attribute est invalide.',
            'in_array' => 'Le champ :attribute n\'existe pas dans :other.',
            'integer' => 'Le champ :attribute doit être un entier.',
            'ip' => 'Le champ :attribute doit être une adresse IP valide.',
            'ipv4' => 'Le champ :attribute doit être une adresse IPv4 valide.',
            'ipv6' => 'Le champ :attribute doit être une adresse IPv6 valide.',
            'json' => 'Le champ :attribute doit être un document JSON valide.',
            'list' => 'Le champ :attribute doit être une liste.',
            'lowercase' => 'Le champ :attribute doit être en minuscules.',
            'lt.array' => 'Le tableau :attribute doit contenir moins de :value éléments.',
            'lt.file' => 'La taille du fichier de :attribute doit être inférieure à :value kilo-octets.',
            'lt.numeric' => 'La valeur de :attribute doit être inférieure à :value.',
            'lt.string' => 'Le texte :attribute doit contenir moins de :value caractères.',
            'lte.array' => 'Le tableau :attribute doit contenir au plus :value éléments.',
            'lte.file' => 'La taille du fichier de :attribute doit être inférieure ou égale à :value kilo-octets.',
            'lte.numeric' => 'La valeur de :attribute doit être inférieure ou égale à :value.',
            'lte.string' => 'Le texte :attribute doit contenir au plus :value caractères.',
            'mac_address' => 'Le champ :attribute doit être une adresse MAC valide.',
            'max.array' => 'Le tableau :attribute ne peut pas contenir plus de :max éléments.',
            'max.file' => 'La taille du fichier de :attribute ne peut pas dépasser :max kilo-octets.',
            'max.numeric' => 'La valeur de :attribute ne peut pas être supérieure à :max.',
            'max.string' => 'Le texte de :attribute ne peut pas contenir plus de :max caractères.',
            'max_digits' => 'Le champ :attribute ne doit pas comporter plus de :max chiffres.',
            'mimes' => 'Le champ :attribute doit être un fichier de type : :values.',
            'mimetypes' => 'Le champ :attribute doit être un fichier de type : :values.',
            'min.array' => 'Le tableau :attribute doit contenir au moins :min éléments.',
            'min.file' => 'La taille du fichier de :attribute doit être supérieure ou égale à :min kilo-octets.',
            'min.numeric' => 'La valeur de :attribute doit être supérieure ou égale à :min.',
            'min.string' => 'Le texte :attribute doit contenir au moins :min caractères.',
            'min_digits' => 'Le champ :attribute doit comporter au moins :min chiffres.',
            'missing' => 'Le champ :attribute doit être manquant.',
            'missing_if' => 'Le champ :attribute doit être manquant quand :other est :value.',
            'missing_unless' => 'Le champ :attribute doit être manquant sauf si :other est :value.',
            'missing_with' => 'Le champ :attribute doit être manquant quand :values est présent.',
            'missing_with_all' => 'Le champ :attribute doit être manquant quand :values sont présents.',
            'multiple_of' => 'La valeur de :attribute doit être un multiple de :value',
            'not_in' => 'Le champ :attribute sélectionné n\'est pas valide.',
            'not_regex' => 'Le format du champ :attribute n\'est pas valide.',
            'numeric' => 'Le champ :attribute doit contenir un nombre.',
            'password.letters' => 'Le champ :attribute doit contenir au moins une lettre.',
            'password.mixed' => 'Le champ :attribute doit contenir au moins une majuscule et une minuscule.',
            'password.numbers' => 'Le champ :attribute doit contenir au moins un chiffre.',
            'password.symbols' => 'Le champ :attribute doit contenir au moins un symbole.',
            'password.uncompromised' => 'Le champ :attribute fourni est apparu dans une fuite de données. Veuillez choisir un autre :attribute.',
            'present' => 'Le champ :attribute doit être présent.',
            'present_if' => 'Le champ :attribute doit être présent quand :other est :value.',
            'present_unless' => 'Le champ :attribute doit être présent sauf si :other est :value.',
            'present_with' => 'Le champ :attribute doit être présent quand :values est présent.',
            'present_with_all' => 'Le champ :attribute doit être présent quand :values sont présents.',
            'prohibited' => 'Le champ :attribute est interdit.',
            'prohibited_if' => 'Le champ :attribute est interdit quand :other est :value.',
            'prohibited_unless' => 'Le champ :attribute est interdit à moins que :other soit dans :values.',
            'prohibits' => 'Le champ :attribute interdit la présence de :other.',
            'regex' => 'Le format du champ :attribute est invalide.',
            'required' => 'Le champ :attribute est obligatoire.',
            'required_array_keys' => 'Le champ :attribute doit contenir des entrées pour : :values.',
            'required_if' => 'Le champ :attribute est obligatoire quand la valeur de :other est :value.',
            'required_if_accepted' => 'Le champ :attribute est obligatoire quand le champ :other a été accepté.',
            'required_unless' => 'Le champ :attribute est obligatoire sauf si :other est :values.',
            'required_with' => 'Le champ :attribute est obligatoire quand :values est présent.',
            'required_with_all' => 'Le champ :attribute est obligatoire quand :values sont présents.',
            'required_without' => 'Le champ :attribute est obligatoire quand :values n\'est pas présent.',
            'required_without_all' => 'Le champ :attribute est requis quand aucun de :values n\'est présent.',
            'same' => 'Les champs :attribute et :other doivent être identiques.',
            'size.array' => 'Le tableau :attribute doit contenir :size éléments.',
            'size.file' => 'La taille du fichier de :attribute doit être de :size kilo-octets.',
            'size.numeric' => 'La valeur de :attribute doit être :size.',
            'size.string' => 'Le texte de :attribute doit contenir :size caractères.',
            'starts_with' => 'Le champ :attribute doit commencer avec une des valeurs suivantes : :values',
            'string' => 'Le champ :attribute doit être une chaîne de caractères.',
            'timezone' => 'Le champ :attribute doit être un fuseau horaire valide.',
            'unique' => 'La valeur du champ :attribute est déjà utilisée.',
            'uploaded' => 'Le fichier du champ :attribute n\'a pu être téléversé.',
            'uppercase' => 'Le champ :attribute doit être en majuscules.',
            'url' => 'Le format de l\'URL de :attribute n\'est pas valide.',
            'ulid' => 'Le champ :attribute doit être un ULID valide.',
            'uuid' => 'Le champ :attribute doit être un UUID valide.',
            'attributes.center_name' => 'Nom du Centre',
            'attributes.name' => 'Nom Complet',
            'attributes.email' => 'Adresse E-mail',
            'attributes.password' => 'Mot de passe',
            'attributes.plan' => 'Forfait'
        ],
        'center/analytics.php' => [
            'general' => 'Analyses'
        ],
        'center/billing.php' => [
            'current_subscription' => 'Abonnement Actuel',
            'expires_at' => 'Expire le',
            'no_active_subscription' => 'Aucun abonnement actif.',
            'available_plans' => 'Forfaits Disponibles',
            'days' => 'Jours',
            'subscribe' => 'S\'abonner',
            'unlimited' => 'Illimité',
            'unknown_package' => 'Forfait Inconnu',
            'currency' => '$'
        ],
        'center/branches.php' => [
            'edit_branch' => 'Modifier la Succursale',
            'create_branch' => 'Créer une Succursale',
            'branch_name' => 'Nom de la Succursale',
            'manager' => 'Gérant',
            'not_assigned' => 'Non attribué',
            'are_you_sure' => 'Êtes-vous sûr ?',
            'no_branches_found' => 'Aucune succursale.',
            'select_manager' => 'Sélectionnez un Gérant',
            'cancel' => 'Annuler',
            'save_changes' => 'Enregistrer'
        ],
        'center/classrooms.php' => [
            'students_count' => '{0} Étudiant|{1} 1 Étudiant|[2,*] :count Étudiants',
            'add_asset' => 'Ajouter un équipement',
            'assets_count' => 'Équipements'
        ],
        'center/courses.php' => [
            'search_placeholder' => 'Rechercher un cours...',
            'status_label' => 'Statut',
            'status_published' => 'Publié',
            'status_draft' => 'Brouillon',
            'status_archived' => 'Archivé',
            'course_name' => 'Nom du Cours',
            'schedules' => 'Horaires',
            'status' => 'Statut',
            'actions' => 'Actions',
            'currency' => '$',
            'not_specified' => 'Non spécifié',
            'content' => 'Contenu',
            'view' => 'Voir',
            'enroll_student' => 'Inscrire l\'étudiant',
            'delete_confirm' => 'Êtes-vous sûr de vouloir supprimer ce cours ?'
        ],
        'center/dashboard.php' => [
            'active_students' => 'Étudiants Actifs',
            'active_courses' => 'Cours Actifs',
            'monthly_expenses' => 'Dépenses Mensuelles',
            'net_profit' => 'Bénéfice Net',
            'recent_activities' => 'Activités Récentes',
            'no_activities' => 'Aucune activité.',
            'currency' => '$',
            'system' => 'Système',
            'enroll_student' => 'Inscrire Étudiant',
            'report' => 'Rapport',
            'projected' => 'Projeté',
            'center_status' => 'Statut du Centre',
            'center_dashboard' => 'Tableau de bord du Centre',
            'system_status' => 'Statut du Système',
            'healthy' => 'En Bonne Santé',
            'real_time_monitoring' => 'Surveillance en temps réel',
            'vs_last_month' => 'vs Mois Dernier',
            'student' => 'Étudiant',
            'observed_pattern' => 'Modèle Observé',
            'action' => 'Action',
            'contact' => 'Contact',
            'overview' => 'Aperçu',
            'advanced_analytics' => 'Analytique Avancée & IA',
            'add_student' => 'Ajouter Étudiant',
            'record_attendance' => 'Présence',
            'collect_fees' => 'Frais',
            'search_student' => 'Rechercher',
            'todays_sessions' => 'Sessions du Jour',
            'scheduled_session' => 'Session planifiée',
            'smart_analytics_center' => 'Centre d\'Analyse Intelligent',
            'financial_reports_ai' => 'Rapports financiers par IA',
            'actions.created' => 'Créé',
            'actions.updated' => 'Mis à jour',
            'actions.deleted' => 'Supprimé',
            'actions.restored' => 'Restauré',
            'actions.Successful Login' => 'Connexion réussie',
            'models.Tenant' => 'Centre',
            'models.User' => 'Utilisateur',
            'models.Student' => 'Étudiant',
            'models.Course' => 'Cours',
            'models.Instructor' => 'Instructeur',
            'models.Branch' => 'Succursale',
            'models.Role' => 'Rôle',
            'models.Subscription' => 'Abonnement',
            'models.SiteSetting' => 'Paramètres',
            'models.Ticket' => 'Billet',
            'models.Sale' => 'Vente',
            'models.package' => 'Forfait',
            'models.coupon' => 'Coupon',
            'ai_early_warning' => 'Système d\'alerte précoce',
            'at_risk_students' => 'Étudiants à risque',
            'risk_level' => 'Niveau de Risque',
            'ai_insights' => 'Insights IA',
            'view_all_risks' => 'Voir tous les risques',
            'course_completion_rate' => 'Taux d\'achèvement',
            'performance_trend' => 'Tendance de performance',
            'insights.high_attrition' => 'Forte attrition dans {subject}.',
            'insights.excellent_performance' => 'Excellente performance {group}.',
            'insights.low_engagement' => 'Faible engagement.',
            'insights.score_drop_detected' => 'Baisse des scores détectée.',
            'insights.inactivity_detected' => 'Inactivité détectée.',
            'insights.upward_trend' => 'Tendance à la hausse.',
            'insights.downward_trend' => 'Tendance à la baisse.',
            'insights.top_performer' => 'Meilleur performeur {course}.',
            'risk_levels.high' => 'Élevé',
            'risk_levels.medium' => 'Moyen',
            'risk_levels.low' => 'Faible',
            'launchpad.title' => 'Bienvenue :name! 🚀',
            'launchpad.subtitle' => 'Complétez ces étapes',
            'launchpad.progress' => 'Progression',
            'launchpad.action' => 'Commencer',
            'launchpad.steps.education_system.title' => 'Système Éducatif',
            'launchpad.steps.education_system.desc' => 'Configurez le système.',
            'launchpad.steps.instructor.title' => 'Instructeur',
            'launchpad.steps.instructor.desc' => 'Ajoutez un instructeur.',
            'launchpad.steps.course.title' => 'Cours',
            'launchpad.steps.course.desc' => 'Créez un cours.',
            'launchpad.steps.student.title' => 'Étudiants',
            'launchpad.steps.student.desc' => 'Inscrivez un étudiant.',
            'launchpad.steps.attendance.title' => 'Présences',
            'launchpad.steps.attendance.desc' => 'Gérez les présences.'
        ],
        'center/instructors.php' => [
            'search_placeholder' => 'Rechercher un instructeur...',
            'specialization' => 'Spécialisation',
            'status' => 'Statut',
            'commission_rate' => 'Taux de Commission (%)',
            'national_id' => 'ID National',
            'gender' => 'Genre',
            'male' => 'Homme',
            'female' => 'Femme',
            'hiring_date' => 'Date d\'embauche',
            'active' => 'Actif',
            'inactive' => 'Inactif',
            'on_hold' => 'En Attente',
            'bio' => 'Biographie',
            'courses_count' => 'Cours',
            'show' => 'Afficher',
            'delete' => 'Supprimer',
            'phone' => 'Téléphone'
        ],
        'center/sales.php' => [
            'select_courses' => 'Sélectionner des Cours',
            'cart' => 'Panier',
            'empty_cart' => 'Le panier est vide',
            'payment_method' => 'Mode de Paiement',
            'paid_amount' => 'Montant Payé',
            'notes' => 'Notes',
            'complete_sale' => 'Compléter la Vente',
            'cash' => 'Espèces',
            'card' => 'Carte de Crédit',
            'bank_transfer' => 'Virement Bancaire',
            'select_student' => 'Sélectionner un Étudiant',
            'item_already_in_cart' => 'Ce cours est déjà dans le panier',
            'please_select_student' => 'Veuillez sélectionner un étudiant'
        ],
        'center/settings.php' => [
            'general.timezone' => 'Fuseau Horaire',
            'academic.attendance_rules' => 'Règles de Présence et Retard',
            'academic.late_levels' => 'Niveaux de Retard',
            'academic.late_levels_help' => 'Définissez les niveaux de retard.',
            'academic.threshold_minutes' => 'Minutes',
            'academic.level_label' => 'Description (ex: Retard léger)',
            'academic.add_level' => 'Ajouter un Niveau',
            'academic.confirm_delete_level' => 'Êtes-vous sûr ?'
        ],
        'center/sidebar.php' => [
            'expenses' => 'Dépenses',
            'questions_bank' => 'Banque de Questions',
            'leaderboard' => 'Classement',
            'student_updated' => 'Étudiant mis à jour',
            'student_deleted' => 'Étudiant supprimé',
            'assets' => 'Équipements',
            'school_management' => 'Gestion Scolaire'
        ],
        'center/students.php' => [
            'export_file' => 'Exporter le Fichier'
        ]
    ]
];

function arrayToCode($array, $indent = 1) {
    if (empty($array)) return '[]';
    $code = "[\n";
    $spaces = str_repeat('    ', $indent);
    foreach ($array as $key => $value) {
        $keyFormatted = is_string($key) ? "'" . addslashes($key) . "'" : $key;
        $code .= $spaces . $keyFormatted . ' => ';
        if (is_array($value)) {
            $code .= arrayToCode($value, $indent + 1) . ",\n";
        } elseif (is_string($value)) {
            $code .= "'" . addslashes($value) . "',\n";
        } elseif (is_bool($value)) {
            $code .= ($value ? 'true' : 'false') . ",\n";
        } elseif (is_numeric($value)) {
            $code .= $value . ",\n";
        } else {
            $code .= "null,\n";
        }
    }
    $code .= str_repeat('    ', $indent - 1) . ']';
    return $code;
}

foreach ($translations as $locale => $files) {
    foreach ($files as $fileKey => $keysToUpdate) {
        list($type, $filename) = explode('/', $fileKey);
        $baseDir = $langDirs[$type];
        $filePath = $baseDir . '/' . $locale . '/' . $filename;
        
        if (!file_exists($filePath)) {
            if (!is_dir(dirname($filePath))) {
                mkdir(dirname($filePath), 0755, true);
            }
            $currentData = [];
        } else {
            $currentData = require $filePath;
        }

        foreach ($keysToUpdate as $dotKey => $value) {
            Arr::set($currentData, $dotKey, $value);
        }

        $code = "<?php\n\nreturn " . arrayToCode($currentData) . ";\n";
        file_put_contents($filePath, $code);
        echo "Updated $filePath\n";
    }
}

echo "French translations applied successfully!\n";
