<?php

namespace Modules\Center\Http\Controllers;

use Modules\Center\Http\Controllers\CenterBaseController as Controller;
use App\Models\Course;
use App\Models\Student;
use App\Models\User;
use App\Models\Enrollment;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use chillerlan\QRCode\QRCode;
use chillerlan\QRCode\QROptions;
use App\Services\FinanceService;

class StudentRegistrationController extends Controller
{
    protected $financeService;

    public function __construct(FinanceService $financeService)
    {
        $this->financeService = $financeService;
    }
    public function index($token)
    {
        $course = Course::where('registration_token', $token)->firstOrFail();
        
        return view('center::groups.register', compact('course'));
    }

    public function store(Request $request, $token)
    {
        $course = Course::where('registration_token', $token)->firstOrFail();

        $request->validate([
            'name' => 'required|string|max:255',
            'phone' => 'required|string|digits:11',
            'parent_phone' => 'required|string|digits:11',
            'email' => 'nullable|email|max:255',
        ]);

        // 1. Check by personal phone number
        $user = User::where('phone', $request->phone)->first();

        // 2. Cross-check by Name + Parent Phone to prevent bypass
        if (!$user) {
            $existingStudent = Student::where('name', $request->name)
                ->where('parent_phone', $request->parent_phone)
                ->where('tenant_id', $course->tenant_id)
                ->first();
            
            if ($existingStudent) {
                $user = $existingStudent->user;
            }
        }

        if (!$user) {
            $email = $request->email ?: ($request->phone . '@' . ($course->tenant->domain ?? 'taalimu') . '.com');
            
            // Check if email already taken (rare case since it's generated by phone, but safe)
            if (User::where('email', $email)->exists() && !$request->email) {
                $email = $request->phone . '_' . Str::random(4) . '@' . ($course->tenant->domain ?? 'taalimu') . '.com';
            }

            $user = User::create([
                'name' => $request->name,
                'email' => $email,
                'phone' => $request->phone,
                'password' => Hash::make($request->phone), // Default password is phone
                'role' => 'student',
                'qr_identifier' => Str::random(12),
                'tenant_id' => $course->tenant_id,
            ]);

            $user->assignRole('student');

            Student::forceCreate([
                'user_id' => $user->id,
                'tenant_id' => $course->tenant_id,
                'name' => $request->name,
                'phone' => $request->phone,
                'parent_phone' => $request->parent_phone,
                'status' => 'active',
            ]);
        } else {
            // Ensure existing user has a qr_identifier if they are a student
            if ($user->role === 'student' && empty($user->qr_identifier)) {
                $user->update(['qr_identifier' => Str::random(12)]);
            }
        }

        // Enroll in the course if not already enrolled
        $isEnrolled = Enrollment::where('user_id', $user->id)
            ->where('course_id', $course->id)
            ->exists();

        if (!$isEnrolled) {
            $this->financeService->createSale([
                'student_id' => $user->student->id,
                'items' => [['id' => $course->id, 'price' => $course->price]],
                'payment_method' => 'cash',
                'paid_amount' => 0,
            ]);
        }

        return redirect()->route('group.registration.success', ['user' => $user->id]);
    }

    public function success(User $user)
    {
        // Get the latest enrollment to show the group/instructor info
        $enrollment = $user->enrollments()->with('course.instructor')->latest()->first();
        $course = $enrollment ? $enrollment->course : null;

        // Use a reliable external QR generator that works across all mobile browsers
        $qrCode = "https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=" . urlencode($user->qr_identifier);
        
        return view('center::groups.registration_success', compact('user', 'qrCode', 'course'));
    }
}
